/**
 * RegForge — AI-ready export.
 *
 * Everything here runs in the browser: the brief is built from the already
 * loaded questionnaire document and turned into a file with a Blob URL. There
 * is no server API, no extra Firestore read and no credential involved. The
 * text contains only what the creator can already see on screen.
 */
import { MODULES, QUESTION_COUNT, MODULE_COUNT, overallProgress, type Answers } from './library';
import { formatAnswer, NOT_ANSWERED } from './answers';
import type { Questionnaire } from './store';

const TITLE = 'RegForge Project Brief';
const RULE = '======================';

/** Deterministic, locale-independent timestamp: "2026-09-29 14:35 UTC". */
export function formatTimestamp(ts: number | null | undefined): string {
  if (ts === null || ts === undefined || !Number.isFinite(ts)) return '—';
  const iso = new Date(ts).toISOString();
  return `${iso.slice(0, 10)} ${iso.slice(11, 16)} UTC`;
}

export function statusLabel(item: Pick<Questionnaire, 'submittedAt'>): string {
  return item.submittedAt ? 'Submitted by client' : 'In progress (not submitted yet)';
}

export function completionLabel(answers: Answers): string {
  const { done, total, percent } = overallProgress(answers);
  return `${done} of ${total} questions answered (${percent}%)`;
}

/** Safe, readable file name such as `daily-bloom-questionnaire.txt`. */
export function briefFilename(item: Pick<Questionnaire, 'title' | 'clientName' | 'token'>, extension = 'txt'): string {
  const base = (item.title || item.clientName || item.token || 'regforge')
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/-{2,}/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 64)
    .replace(/-+$/g, '');
  return `${base || 'regforge'}-questionnaire.${extension}`;
}

/**
 * Plain-text brief, laid out to be pasted straight into an AI tool.
 *
 * The share token is deliberately omitted: it is a bearer capability for the
 * client link, so it must never travel inside a document meant to be pasted
 * into another service.
 */
export function buildTxtBrief(item: Questionnaire): string {
  const lines: string[] = [
    TITLE,
    RULE,
    '',
    `Project: ${item.title || 'Untitled project'}`,
    `Client: ${item.clientName || '—'}`,
    `Client email: ${item.clientEmail || '—'}`,
    `Status: ${statusLabel(item)}`,
    `Completion: ${completionLabel(item.answers)}`,
    `Created: ${formatTimestamp(item.createdAt)}`,
    `Last updated: ${formatTimestamp(item.updatedAt)}`,
    `Submitted: ${item.submittedAt ? formatTimestamp(item.submittedAt) : 'Not submitted yet'}`,
    '',
    `${MODULE_COUNT} modules · ${QUESTION_COUNT} questions · answers stored as typed, budget in INR (₹)`,
  ];

  for (const module of MODULES) {
    lines.push('', `## ${module.title}`, '');
    module.questions.forEach((question, index) => {
      const formatted = formatAnswer(question, item.answers[question.id]);
      lines.push(`Question ID: ${question.id}`);
      lines.push(`Question: ${question.label}`);
      if (formatted.list && formatted.list.length > 0) {
        lines.push('Answer:');
        for (const entry of formatted.list) lines.push(`- ${entry}`);
        if (formatted.legacy && formatted.note) lines.push(`  (${formatted.note})`);
      } else if (!formatted.answered) {
        lines.push(`Answer: ${NOT_ANSWERED}`);
      } else if (formatted.legacy && formatted.note) {
        lines.push(`Answer: ${formatted.text} (${formatted.note})`);
      } else {
        lines.push(`Answer: ${formatted.text}`);
      }
      if (question.required) lines.push('Required: yes');
      if (index < module.questions.length - 1) lines.push('');
    });
  }

  lines.push(
    '',
    '---',
    'Generated by RegForge from the creator’s private workspace.',
    'The client share link and token are intentionally not included in this export.',
    '',
  );
  return lines.join('\n');
}

interface JsonAnswer {
  id: string;
  label: string;
  type: string;
  required: boolean;
  answered: boolean;
  legacy: boolean;
  answer: string | string[] | null;
  budgetINR: string | null;
}

/** Optional structured export — same data as the TXT brief, machine friendly. */
export function buildJsonBrief(item: Questionnaire): string {
  const modules = MODULES.map((module) => ({
    key: module.key,
    title: module.title,
    questions: module.questions.map<JsonAnswer>((question) => {
      const formatted = formatAnswer(question, item.answers[question.id]);
      return {
        id: question.id,
        label: question.label,
        type: question.type,
        required: Boolean(question.required),
        answered: formatted.answered,
        legacy: formatted.legacy,
        answer: !formatted.answered ? null : formatted.list ?? formatted.text,
        budgetINR: question.type === 'currency' && formatted.answered ? formatted.text : null,
      };
    }),
  }));

  return `${JSON.stringify(
    {
      generator: 'RegForge',
      format: 'regforge.brief.v1',
      questionnaire: {
        // No share token here either — see buildTxtBrief.
        project: item.title,
        client: item.clientName,
        clientEmail: item.clientEmail,
        status: item.submittedAt ? 'submitted' : 'in_progress',
        completion: completionLabel(item.answers),
        createdAt: new Date(item.createdAt).toISOString(),
        updatedAt: new Date(item.updatedAt).toISOString(),
        submittedAt: item.submittedAt ? new Date(item.submittedAt).toISOString() : null,
        currency: 'INR',
      },
      modules,
    },
    null,
    2,
  )}\n`;
}

/** Save text as a file using a Blob URL — browser only, no server round-trip. */
export function downloadTextFile(
  filename: string,
  text: string,
  mime = 'text/plain;charset=utf-8',
): boolean {
  if (typeof document === 'undefined') return false;
  try {
    const blob = new Blob([text], { type: mime });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = filename;
    anchor.rel = 'noopener';
    anchor.style.display = 'none';
    document.body.appendChild(anchor);
    anchor.click();
    anchor.remove();
    window.setTimeout(() => URL.revokeObjectURL(url), 2000);
    return true;
  } catch (error) {
    console.warn('[regforge] download failed', error);
    return false;
  }
}

/** Clipboard write with a legacy fallback; resolves false instead of throwing. */
export async function copyToClipboard(text: string): Promise<boolean> {
  if (typeof document === 'undefined') return false;
  try {
    if (navigator.clipboard?.writeText) {
      await navigator.clipboard.writeText(text);
      return true;
    }
  } catch (error) {
    console.warn('[regforge] clipboard API unavailable, trying fallback', error);
  }

  try {
    const area = document.createElement('textarea');
    area.value = text;
    area.setAttribute('readonly', 'true');
    area.style.position = 'fixed';
    area.style.top = '-1000px';
    area.style.opacity = '0';
    document.body.appendChild(area);
    area.select();
    area.setSelectionRange(0, text.length);
    const ok = document.execCommand('copy');
    area.remove();
    return ok;
  } catch (error) {
    console.warn('[regforge] clipboard fallback failed', error);
    return false;
  }
}
